# -*- coding: utf-8 -*-
"""BioinformáticaLab8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148DgsW7yZY-VetxUa5fUaCzBv5WsEO4d

# Ejercicio 1 y 2
"""

secuencias_ejercicio_1 = [
    "ATCGTACGATGACCTGATCG",
    "GGTATACGATGACGTTACCA",
    "TTTCTACGATGACCATAGGT",
    "AACGTACGATGACGGGTTAA",
    "CGGATACGATGACTTCCGTA",
    "TACCTACGATGACAGGTACA",
    "GACTTACGATGACCGATAGC",
    "TCGATACGATGACTGGCAAT",
    "AGGCTACGATGACATTCGGA",
    "CCTATACGATGACGGAATTC"
]

def obtener_k_mers_frecuentes(secuencias, k):
    conteo_k_mers = {}
    for secuencia in secuencias:
        k_mers_vistos = set()
        for i in range(len(secuencia) - k + 1):
            k_mer = secuencia[i:i+k]
            k_mers_vistos.add(k_mer)
        for k_mer in k_mers_vistos:
            conteo_k_mers[k_mer] = conteo_k_mers.get(k_mer, 0) + 1

    max_frecuencia = max(conteo_k_mers.values())
    k_mers_mas_frecuentes = {k_mer: frec for k_mer, frec in conteo_k_mers.items() if frec == max_frecuencia}
    return k_mers_mas_frecuentes

k_mers_7 = obtener_k_mers_frecuentes(secuencias_ejercicio_1, 7)
k_mers_8 = obtener_k_mers_frecuentes(secuencias_ejercicio_1, 8)
k_mers_9 = obtener_k_mers_frecuentes(secuencias_ejercicio_1, 9)

print("Mejores k-mers k=7:", k_mers_7)
print("Mejores k-mers k=8:", k_mers_8)
print("Mejores k-mers k=9:", k_mers_9)

"""# Ejercicio 3"""

mejor_k_mer_9 = list(k_mers_9.keys())[0]

posiciones_ocurrencias = []
for i, secuencia in enumerate(secuencias_ejercicio_1):
    posicion = secuencia.find(mejor_k_mer_9)
    posiciones_ocurrencias.append((i, posicion))

print("Posiciones del k-mer candidato en cada secuencia:", posiciones_ocurrencias)

"""# Ejercicio 4 Y 5"""

alineamiento_multiple = []
longitud_motif = len(mejor_k_mer_9)

for secuencia in secuencias_ejercicio_1:
    posicion = secuencia.find(mejor_k_mer_9)
    if posicion != -1:
        region_extraida = secuencia[posicion:posicion+longitud_motif]
        alineamiento_multiple.append(region_extraida)

for secuencia_alineada in alineamiento_multiple:
    print(secuencia_alineada)

"""# Ejercicio 6"""

nucleotidos = ['A', 'C', 'G', 'T']
matriz_frecuencias = {n: [0] * longitud_motif for n in nucleotidos}

for secuencia in alineamiento_multiple:
    for posicion, nucleotido in enumerate(secuencia):
        matriz_frecuencias[nucleotido][posicion] += 1

for nucleotido in nucleotidos:
    print(f"{nucleotido}: {matriz_frecuencias[nucleotido]}")

"""# Ejercicio 7"""

secuencia_consenso = ""

for posicion in range(longitud_motif):
    max_frecuencia = -1
    nucleotido_frecuente = ""
    for nucleotido in nucleotidos:
        frecuencia_actual = matriz_frecuencias[nucleotido][posicion]
        if frecuencia_actual > max_frecuencia:
            max_frecuencia = frecuencia_actual
            nucleotido_frecuente = nucleotido
    secuencia_consenso += nucleotido_frecuente

print("Secuencia consenso:", secuencia_consenso)

"""# Ejercicio 8"""

total_secuencias = len(alineamiento_multiple)
porcentajes_conservacion = []
posiciones_totalmente_conservadas = []
posiciones_variables = []

for posicion in range(longitud_motif):
    nucleotido_consenso = secuencia_consenso[posicion]
    frecuencia_consenso = matriz_frecuencias[nucleotido_consenso][posicion]
    porcentaje = (frecuencia_consenso / total_secuencias) * 100
    porcentajes_conservacion.append(porcentaje)

    if porcentaje == 100.0:
        posiciones_totalmente_conservadas.append(posicion)
    else:
        posiciones_variables.append(posicion)

porcentaje_global = sum(porcentajes_conservacion) / longitud_motif

print("Porcentajes por posición:", porcentajes_conservacion)
print("Posiciones 100% conservadas:", posiciones_totalmente_conservadas)
print("Posiciones variables:", posiciones_variables)
print("Conservación global (%):", porcentaje_global)

"""# Ejercicio 9"""

numero_secuencias_con_motif = len(alineamiento_multiple)

print("Longitud del motif encontrado:", longitud_motif)
print("Secuencia consenso del motif:", secuencia_consenso)
print("Número de secuencias que contienen el motif:", numero_secuencias_con_motif)

"""# Ejercicio 10"""

texto_crudo_anexo_1 = """>S1
ATCGGCTAACGTAGCTAGCTTGACCGTACGATCGATCGGATCGTAGCTAGCATCGATCGTACGATC
GATGCTAGCTAGCATCGATCGATACGATCGTAGCTAGCTACGTAGCTAGCTACGTAGCTTACGATG
ACGGTACCGATCGATCGTAGCTAACGTA
>S2
GCTAGCTAGCATCGATCGTAGCTAGCTAGCGATCGTAGCTAGCATCGATCGATCGTAGCTAGCTAG
CATCGATCGATCGTAGCTAGCTAGCATCGATACGTAGCTACGTACGATGACATCGTAGCTAGCTAA
CGTAGCTAGCTAGCGATCGTAGCTAGCTA
>S3
CGTAGCTAGCTAGCATCGATCGTAGCTAACGTAGCTAGCATCGATCGTAGCTAGCTAGCATCGATC
GATCGTAGCTAGCTAACGTAGCTAGCTAGCATCGATCGTAGCTAGCTACGTACGATGATCGATCGT
AGCTAACGTAGCTAGCTAGCATCGATCGTA
>S4
AACGTAGCTAGCTAGCATCGATCGTAGCTAGCTAACGTAGCTAGCTAGCATCGATCGTAGCTAGCA
TCGATCGTAGCTAACGTAGCTAGCTAGCATCGATCGTAGCTAGCTACGTATACGATGACGCTAGCT
AACGTAGCTAGCATCGATCGTAGCTAACGT
>S5
TAGCTAGCATCGATCGTAGCTAACGTAGCTAGCTAGCATCGATCGTAGCTAACGTAGCTAGCATCG
ATCGTAGCTAACGTAGCTAGCTAGCATCGATCGTAGCTAGCTAACGTATACGATGTCCGTAGCTAA
CGTAGCTAGCTAGCATCGATCGTAGCTAACG
>S6
GATCGTAGCTAACGTAGCTAGCATCGATCGTAGCTAACGTAGCTAGCTAGCATCGATCGTAGCTAA
CGTAGCTAGCATCGATCGTAGCTAACGTAGCTAGCTAGCATCGATCGTAGCTATACGATGACGATC
GTAGCTAACGTAGCTAGCATCGATCGTAGCT
>S7
CTAGCTAACGTAGCTAGCATCGATCGTAGCTAACGTAGCTAGCATCGATCGTAGCTAACGTAGCTA
GCTAGCATCGATCGTAGCTAACGTAGCTAGCATCGATCGTAGCTAACGTATACGATGCCGCTAACG
TAGCTAGCATCGATCGTAGCTAACGTAGCTA
>S8
CGATCGTAGCTAACGTAGCTAGCATCGATCGTAGCTAACGTAGCTAGCTAGCATCGATCGTAGCTA
ACGTAGCTAGCATCGATCGTAGCTAACGTAGCTAGCTAGCATCGATCGTAGCTATACGATGACCGT
AGCTAACGTAGCTAGCATCGATCGTAGCTAAC"""

secuencias_anexo_1 = []
secuencia_temporal = ""

for linea in texto_crudo_anexo_1.strip().split('\n'):
    linea_limpia = linea.strip()
    if linea_limpia.startswith(">"):
        if secuencia_temporal:
            secuencias_anexo_1.append(secuencia_temporal)
            secuencia_temporal = ""
    else:
        secuencia_temporal += linea_limpia

if secuencia_temporal:
    secuencias_anexo_1.append(secuencia_temporal)

k_mers_9_anexo = obtener_k_mers_frecuentes(secuencias_anexo_1, 9)
print("Mejores k-mers k=9 en Anexo 1:\n", k_mers_9_anexo)